FROM balrog-base:latest

WORKDIR /opt/balrog

# Copy wheels before the main project files
COPY wheels/ /opt/balrog/wheels/

COPY . /opt/balrog/

# Only install project if it's not already installed
RUN if ! /opt/conda/bin/python -m pip show balrog > /dev/null; then \
        /opt/conda/bin/python -m pip install '.' && \
        /opt/conda/bin/python post_install.py; \
    fi

CMD ["/bin/bash"]

# docker build -f docker/Dockerfile_Mac -t balrog:1 .
# docker run -it -v ./results:/opt/balrog/results balrog:1