FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    python3-venv \
    unzip \
    vim \
    tmux \
    git \
    build-essential \
    libglib2.0-dev \
    ninja-build \
    curl \
    wget \
    libgl1-mesa-glx

ARG PYTHON_VERSION=3.10
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/conda_setup

# Set up conda environment
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh -O miniconda.sh && \
    chmod +x miniconda.sh && \
    ./miniconda.sh -b -p /opt/conda && \
    /opt/conda/bin/conda install -y python=$PYTHON_VERSION && \
    /opt/conda/bin/conda clean -ya && \
    /opt/conda/bin/python -m pip install --upgrade pip ipython ipdb

ENV PATH=/opt/conda/bin:$PATH

# Install Python packages from requirements.txt
COPY requirements.txt .
RUN /opt/conda/bin/python -m pip install -r requirements.txt

CMD ["/bin/bash"]

# docker build -f docker/Dockerfile_Base_Mac -t balrog-base:latest .