#!/bin/bash

# Create a temporary Docker container to build the wheel
docker run --rm -v $(pwd):/work -w /work nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04 bash -c "
    apt-get update && \
    apt-get install -y python3-pip python3-dev build-essential git && \
    pip install wheel && \
    python3 -m pip wheel balrog-nle && \
    ls -l *.whl
"